services:
  fastapi:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "80:80"  # Change this line to use port 80
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
    command: /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf